version: "3.1"
services:
    php-fpm:
        build: .
        volumes:
            - "./code:/code"
            - "./configs/msmtprc:/etc/msmtprc"
            - "./configs/mail.ini:/usr/local/etc/php/conf.d/mail.ini"
    web:
        image: "nginx:latest"
        ports:
            - "80:80"
        volumes:
            - "./code:/code"
            - "./configs/site.conf:/etc/nginx/conf.d/site.conf"
        depends_on:
            - php-fpm
    db:
        image: "mysql"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - "./configs/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
        environment:
            - MYSQL_ROOT_PASSWORD=password
    admin:
        image: "phpmyadmin/phpmyadmin"
        ports:
            - "8082:80"
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=password
    mail:
        image: "namshi/smtp"