<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
    <title>Регулярные выражения</title>
    <style>
        .wrapper {
            padding: 10px;
        }

        h3, p, form {
            margin: 10px;
        }

        * {
            font: 20px serif;
            box-sizing: border-box;
        }

        input, label {
            margin: 5px 0;
        }

        input, select {
            padding: 10px;
        }
    </style>
</head>
<body>
<div class="wrapper">
    <form action="/" method="post" enctype="multipart/form-data" name="form">
        <label for="file">Выберите файл:</label>
        <input type="file" size="10" name="file">
        <br><input type="submit" value="Отправить">
    </form>
    <?php

    use function DateParser\parseDates;

    function printTable($source, $modified)
    {
        echo <<<'END'
<style>
        .compare {
            display: grid;
            grid-template-columns: 1fr 1fr;
        }
        .compare__item {
            width: auto;
            padding: 5px;
            margin: 5px;
            border: 1px solid lightgoldenrodyellow;
        }
        .date__color_red
        {
            color: red;
        };
        }
        @media only screen and (max-width: 600px) {
            .compare {
                grid-template-columns: 1fr;
            }
        }
    </style>
END;
        echo '<div class="compare"><pre class="compare__item">';
        echo $source;
        echo '</pre>';
        echo '<pre class="compare__item">';
        echo $modified;
        echo '</pre>';
        echo '</div>';
    }

    if (isset($_FILES['file'])) {
        if ($_FILES['file']['error'] === UPLOAD_ERR_OK) {
            $fileContents = file_get_contents($_FILES['file']['tmp_name']);
            $parsedFile = parseDates($fileContents);
        }
        printTable($fileContents, $parsedFile);
    }
    ?>

</div>
</body>
</html>