<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
    <link rel="stylesheet" href="main.css">
    <title>Регулярные выражения</title>
</head>
<body>
<div class="wrapper">
    <form action="/" method="post" enctype="multipart/form-data" name="form">
        <label for="file">Выберите файл:</label>
        <input type="file" size="10" name="file" required>
        <br><input type="submit" value="Отправить">
    </form>
    <?php

    require_once "modules/dateParser.php";

    use function DateParser\{parseDates, printTable};

    if (isset($_FILES['file'])) {
        if ($_FILES['file']['error'] === UPLOAD_ERR_OK) {
            $fileContents = file_get_contents($_FILES['file']['tmp_name']);
            $parsedFile = parseDates($fileContents);
        }
        printTable($fileContents, $parsedFile);
    }
    ?>
</div>
</body>
</html>