<main>
    <form>
        <div class="form-row">
            <div class="col-25">
                <label for="author">Автор:</label>
            </div>
            <div class="col-75">
                <input type="text" id="author" autocomplete="off" class="add-form-inputs">
            </div>
        </div>
        <div class="form-row">
            <div class="col-25">
                <label for="name">Название:</label>
            </div>
            <div class="col-75">
                <input type="text" id="name" autocomplete="off" class="add-form-inputs">
            </div>
        </div>
        <div class="form-row">
            <div class="col-25">
                <label for="text">Текст:</label>
            </div>
            <div class="col-75">
                <textarea class="add-form-inputs" autocomplete="off"></textarea>
            </div>
        </div>
        <div class="form-row">
            <input type="submit" id="add-button" class="button" value="Отправить">
        </div>
    </form>
</main>