<main class="row">
  <section id="popular-songs" class="main-section">
    <h2>Популярные подборы</h2>
    <ul>
      <li><a href="kukushka">Виктор Цой &ndash; Кукушка</a></li>
      <li><a href="tam_gde_klen_shymit">Синяя птица &ndash; Там где клён шумит</a></li>
      <li><a href="#">Abba &ndash; Happy New Year</a></li>
      <li><a href="#">Eagles &ndash; Hotel California</a></li>
      <li><a href="#">Barry Manilow &ndash; Copacabana</a></li>
    </ul>
  </section>
  <section id="popular-authors" class="main-section">
      <h2>Популярные исполнители</h2>
      <ul>
        <li><a href="#">Виктор Цой</a></li>
        <li><a href="#">Синяя птица</a></li>
        <li><a href="#">Abba</a></li>
        <li><a href="#">Eagles</a></li>
        <li><a href="#">Barry Manilow</a></li>
      </ul>
    </section>
</main>