<main class="row">
    <section id="popular-songs" class="main-section">
        <h2>Популярные подборы</h2>
        <ul>
            <?php
            foreach ($this->songs as $link => $text) {
                echo '<li><a href="' . $link . '">' . $text . '</a></li>';
            }
            ?>
        </ul>
    </section>
    <section id="popular-authors" class="main-section">
        <h2>Популярные исполнители</h2>
        <ul>
            <?php
            foreach ($this->authors as $author => $text) {
                echo '<li><a href="#">' . $text . '</a></li>';
            }
            ?>
        </ul>
    </section>
</main>