<main>
  <article>
      <header>
          <h1>Виктор Цой &ndash; Кукушка</h1>
          <time datetime="2019-03-29">29.03.2019</time>
        </header>
        <div id="play-settings">
          <div class="play-setting">Прокрутка:<button class="btn-setting">-</button><button class="btn-setting">+</button></div>
          <div class="play-setting">Шрифт:<button class="btn-setting">-</button><button class="btn-setting">+</button></div>
          <div class="play-setting">Тональность:<button class="btn-setting">-</button><button class="btn-setting">+</button></div>

        </div>
    <pre>
Вступление: <b>Am</b> | <b>C</b> | <b>G</b> | <b>F</b>

<b>Am</b>                           <b>C</b>
Песен, еще не написанных, сколько?
<b>G</b> <b>Dm</b>
Скажи, кукушка,
<b>Am</b>
Пропой.
<b>Am</b>                            
В городе мне жить или на выселках?
<b>C</b>
Камнем лежать
<b>G</b> <b>Dm</b>
Или гореть звездой?
<b>Am</b>
Звездой...

Припев:
<b>G</b>          <b>F</b>               <b>Am</b>
Солнце мое, взгляни на меня:
<b>G</b>       <b>F</b>                     <b>Am</b>
Моя ладонь превратилась в кулак.
<b>G</b>             <b>F</b>            <b>Am</b> <b>G</b> <b>F</b>
И если есть порох, дай огня.
<b>Am</b>
Вот так.

Проигрыш: <b>Am</b> | <b>C</b> | <b>G</b> | <b>F</b>

<b>Am</b>              
Кто пойдет по следу одинокому?
<b>C</b>                                  <b>G</b> <b>Dm</b>
Сильные да смелые головы сложили в поле,
<b>Am</b>              
В бою.
<b>Am</b>              
Мало кто остался в светлой памяти,
<b>C</b>                                     <b>G</b> <b>Dm</b>
В трезвом уме да с твердой рукой в строю.
<b>Am</b>              
В строю.

Припев:
<b>G</b>          <b>F</b>               <b>Am</b>
Солнце мое, взгляни на меня:
<b>G</b>       <b>F</b>                     <b>Am</b>
Моя ладонь превратилась в кулак.
<b>G</b>             <b>F</b>            <b>Am</b> <b>G</b> <b>F</b>
И если есть порох, дай огня.
<b>Am</b>
Вот так.

<b>Am</b>                  
Где же ты теперь, воля вольная,
<b>C</b>                                        <b>G</b>  <b>Dm</b>
С кем же ты сейчас ласковый рассвет встречаешь?
<b>Am</b>              
Ответь!
<b>Am</b>                 
Хорошо с тобой да плохо без тебя.
<b>C</b>                              <b>G</b>  <b>Dm</b>
Голову да плечи терпеливые под плеть.
<b>Am</b>              
Под плеть.

Припев: 
<b>G</b>          <b>F</b>               <b>Am</b>
Солнце мое, взгляни на меня:
<b>G</b>       <b>F</b>                     <b>Am</b>
Моя ладонь превратилась в кулак.
<b>G</b>             <b>F</b>            <b>Am</b> <b>G</b> <b>F</b>
И если есть порох, дай огня.
<b>Am</b>
Вот так.
<b>G</b>          <b>F</b>               <b>Am</b>
Солнце мое, взгляни на меня:
<b>G</b>       <b>F</b>                     <b>Am</b>
Моя ладонь превратилась в кулак.
<b>G</b>             <b>F</b>            <b>Am</b> <b>G</b> <b>F</b>
И если есть порох, дай огня.
<b>Am</b>
Вот так.</pre>
</article>
</main>