<main>
    <article>
        <header>
            <h1><?= $this->title ?></h1>
            <time datetime="2019-03-29">29.03.2019</time>
        </header>
        <div id="play-settings">
            <div class="play-setting">Прокрутка:
                <button class="btn-setting">-</button>
                <button class="btn-setting">+</button>
            </div>
            <div class="play-setting">Шрифт:
                <button class="btn-setting">-</button>
                <button class="btn-setting">+</button>
            </div>
            <div class="play-setting">Тональность:
                <button class="btn-setting">-</button>
                <button class="btn-setting">+</button>
            </div>
        </div>
        <pre><?= $this->text ?></pre>
    </article>
    <script src="https://unpkg.com/tone@13.8.25/build/Tone.js"></script>
    <script>
        var stringTransposes = {
            "Am": [0, 1, 2, 2, 0, 0], 
            "C":  [0, 1, 0, 2, 3, 0], 
            "Dm": [1, 3, 2, 0, 'x', 'x'],
            "D":  [2, 3, 2, 0, 'x', 'x'],
            "G":  [3, 0, 0, 0, 2, 3], 
            "F":  [1, 1, 2, 3, 3, 1],
            "E7": [0, 1, 3, 2, 3,'x'],
            "B7": [2, 0, 2, 1, 2, 'x']
        };
        var tuning = ["E4", "B3", "G3", "D3", "A2", "E2"];

        function playChord(chord) {
            var transposes = stringTransposes[chord];
            var transposedChord = [];
            for (var i = 0; i < transposes.length; i++)
            {
                if (transposes[i] != 'x')
                {
                    var frequency = Tone.Frequency(tuning[i]);
                    var transposing = transposes[i];
                    var transposedNote = frequency.transpose(transposing);
                    transposedChord[i] = transposedNote;
                }
            }
            var polySynth = new Tone.PolySynth(6, Tone.Synth).toMaster();
            polySynth.triggerAttackRelease(transposedChord, "8n");
        }

        var chords = document.getElementsByClassName("chord");
        for (let chord of chords) {
            chord.addEventListener("click", function(e) {
                playChord(this.innerHTML);
            })
        }
    </script>
</main>