<main>
    <article>
        <header>
            <h1><?= $this->title ?></h1>
            <time datetime="2019-03-29">29.03.2019</time>
        </header>
        <div id="play-settings">
            <div class="play-setting">Прокрутка:
                <button class="btn-setting">-</button>
                <button class="btn-setting">+</button>
            </div>
            <div class="play-setting">Шрифт:
                <button class="btn-setting">-</button>
                <button class="btn-setting">+</button>
            </div>
            <div class="play-setting">Тональность:
                <button class="btn-setting">-</button>
                <button class="btn-setting">+</button>
            </div>
        </div>
        <pre><?= $this->text ?></pre>
    </article>
</main>