<main>
  <article>
      <header>
          <h1>Синяя птица &ndash; Там, где клён шумит</h1>
          <time datetime="2019-03-29">29.03.2019</time>
        </header>
        <div id="play-settings">
          <div class="play-setting">Прокрутка:<button class="btn-setting">-</button><button class="btn-setting">+</button></div>
          <div class="play-setting">Шрифт:<button class="btn-setting">-</button><button class="btn-setting">+</button></div>
          <div class="play-setting">Тональность:<button class="btn-setting">-</button><button class="btn-setting">+</button></div>

        </div>
<pre>Вступление: <b>Am</b> | <b>Am/G</b> | <b>Am/F#</b> | <b>Am/F</b> <b>Am/E</b>

      <b>Am</b>               <b>F</b>
 Там, где клён шумит над речной волной, 
<b>Am</b>           <b>F</b>
 Говорили мы о любви с тобой, 
 <b>Dm</b>              <b>G</b>            <b>C</b>
 Отшумел тот клён, в поле бродит мгла, 
 <b>Dm</b>               <b>Am</b>        <b>E7</b>   <b>Am</b>
 А любовь, как сон, стороной прошла. 
          <b>D</b>        <b>G</b>        <b>C</b>
 А любовь, как сон, а любовь, как сон, 
<b>Am</b>        <b>B7</b>      <b>F</b>      <b>E7</b> <b>Am</b>
 А любовь, как сон, стороной прошла. 
 
      <b>Am</b>               <b>F</b>
 Сердцу очень жаль, что случилось так, 
      <b>Am</b>               <b>F</b>
 Гонит осень вдаль журавлей косяк. 
 <b>Dm</b>              <b>G</b>            <b>C</b>
 Четырём ветрам грусть-печаль раздам, 
 <b>Dm</b>               <b>Am</b>        <b>E7</b>  <b>Am</b>
 Не вернётся вновь это лето к нам.
          <b>D</b>        <b>G</b>         <b>C</b> 
 Не вернётся вновь, не вернётся вновь, 
<b>Am</b>        <b>B7</b>      <b>F</b>      <b>E7</b> <b>Am</b>
 Не вернётся вновь это лето к нам. 
 
      <b>Am</b>               <b>F</b>
 Ни к чему теперь за тобой ходить, 
      <b>Am</b>               <b>F</b>
 Ни к чему теперь мне цветы дарить, 
 <b>Dm</b>              <b>G</b>            <b>C</b>
 Ты любви моей не смогла сберечь, 
 <b>Dm</b>               <b>Am</b>        <b>E7</b> <b>Am</b>
 Поросло травой место наших встреч.
          <b>D</b>        <b>G</b>     <b>C</b>
 Поросло травой, поросло травой, 
<b>Am</b>        <b>B7</b>      <b>F</b>     <b>E7</b> <b>Am</b>
 Поросло травой место наших встреч.</pre>
</article>
</main>