<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= isset($this->values['pageTitle']) ? $this->values['pageTitle']:'no title' ?></title>
</head>
<body>
    <h1>My template</h1>
    <main>
        <?php
            $this->main();
        ?>
    </main>
</body>
</html>